# Generated by Django 4.2.7 on 2023-11-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='categoriesimage/')),
                ('order_number', models.IntegerField()),
            ],
            options={
                'ordering': ['-order_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=300)),
                ('previous_price', models.IntegerField(blank=True, null=True)),
                ('current_price', models.IntegerField()),
                ('short_descriptions', models.TextField()),
                ('order_number', models.IntegerField()),
            ],
        ),
    ]
