# Generated by Django 4.2.7 on 2023-11-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsets',
            options={'ordering': ['order_number']},
        ),
        migrations.AddField(
            model_name='questionsets',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_categorie', to='app.categories'),
            preserve_default=False,
        ),
    ]
