# Generated by Django 4.2.7 on 2023-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_questionsets_options_questionsets_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsets',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='questionsets',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='questionsets',
            name='short_descriptions',
        ),
        migrations.AddField(
            model_name='categories',
            name='current_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='previous_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='short_descriptions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
