# Generated by Django 4.2.7 on 2023-11-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='setname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='app.questionsets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.questions'),
        ),
    ]
