# Generated by Django 4.2.7 on 2023-11-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questions_setname_alter_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='title',
            new_name='question',
        ),
    ]
