# Generated by Django 4.2.7 on 2023-11-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_title_questions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='setname',
        ),
        migrations.AddField(
            model_name='questions',
            name='set_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.questionsets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.questions'),
        ),
        migrations.AlterField(
            model_name='questionsets',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_sets', to='app.categories'),
        ),
    ]
