# Generated by Django 4.2.7 on 2023-11-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_questions_setname_questions_set_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsets',
            name='is_free',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionsets',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('peending', 'Peending')], default='peending', max_length=200),
        ),
    ]
