# Generated by Django 4.2.7 on 2023-11-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_questionsets_is_free_questionsets_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsets',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=200),
        ),
    ]
