# Generated by Django 4.2.7 on 2023-11-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsets',
            name='payment_status',
        ),
    ]
