# Generated by Django 4.2.7 on 2023-11-21 10:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_questionsets_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categories_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='categories_name', unique=True),
        ),
    ]
