# Generated by Django 4.2.7 on 2023-11-21 10:25

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_categories_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='question', unique=True),
        ),
        migrations.AddField(
            model_name='questionsets',
            name='questions_set_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='set_name', unique=True),
        ),
        migrations.AlterField(
            model_name='questionsets',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='app.categories'),
        ),
    ]
