# Generated by Django 4.2.7 on 2023-12-03 12:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_slider_alter_answer_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='short_descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
