# Generated by Django 4.2.7 on 2023-12-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='short_descriptions',
            field=models.TextField(),
        ),
    ]
