# Generated by Django 4.2.7 on 2023-12-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_categories_short_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPatner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qr_code', models.ImageField(upload_to='qr/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='purchases',
            name='payment_method',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='app.paymentpatner'),
        ),
    ]
