# Generated by Django 4.2.7 on 2024-01-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_paymentpatner_alter_purchases_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='answerimage/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='answerimage/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='questionaudio/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='questionImg/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='set_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_set_name', to='app.questionsets'),
        ),
    ]
