# Generated by Django 4.2.7 on 2024-01-22 11:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_answer_audio_answer_image_questions_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='short_descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(),
        ),
    ]
