# Generated by Django 4.2.7 on 2024-02-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_answer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionset', to='app.categories'),
        ),
    ]
