# Generated by Django 4.2.7 on 2024-02-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_score_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='set_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_set_id', to='app.questionsets'),
            preserve_default=False,
        ),
    ]
