# Generated by Django 4.2.7 on 2024-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_group_questions_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
